import { Inter, Geist, Geist_Mono } from "next/font/google"
import { ThemeProvider } from "next-themes"
import type React from "react"
import type { Metadata } from "next"

import { MainNav } from "@/components/main-nav"
import { ThemeToggle } from "@/components/theme-toggle"
import { UserNav } from "@/components/user-nav"
import { SidebarProvider } from "@/components/ui/sidebar"

import "./globals.css"

const inter = Inter({ subsets: ["latin"] })
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="light">
          <SidebarProvider>
            <div className="flex min-h-screen">
              <MainNav />
              <div className="flex-1">
                <header className="flex h-14 items-center gap-4 border-b bg-background px-6">
                  <div className="flex-1" />
                  <ThemeToggle />
                  <UserNav />
                </header>
                <main className="flex-1 space-y-4 p-8 pt-6">{children}</main>
              </div>
            </div>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
